### ISSUE TITLE
Information on Interaction Sites

### ISSUE THREAD

**Issue by jjhuy-wq** [Ibvt/RNAnue#22]
Hello Richard,
is it possible to also get information about the actual interaction sites for an interaction?

**Comment by riasc** [comment]
Hi, 
thanks for requesting this. It was planned, but I'm currently only fixing final bugs, but there will be some movement in this project as @ChristopherAdelmann will take over. I'm sure he has something planned in that direction.

Thanks

**Comment by riasc** [comment]
I will close this.. let us know if you have any other questions and feel free to reopen this
