### ISSUE TITLE
Running RNAnue from container 

### ISSUE THREAD

**Issue by Egors01** [Ibvt/RNAnue#8]
Hello, 

Thank you for creating the pipeline. 

I am encountering problems when trying to run the RNAnue from the docker container
I have PE reads and use the config file created from the template provided here. The file is attached

When I run: 
	_singularity exec rnanue_latest.sif /RNAnue/build/RNAnue subcall -c /data/meyer/egor/RNAnue_pipeline/params.cfg_

I got the following output whtout downstream errors/warnings or other output. 
```
	after parameters
	RNAnue v0.1.0 - Detect RNA-RNA interactions from Direct-Duplex-Detection (DDD) data.
	create Base
	"Ja gut aehh..." - Randy OR  <some random citation>
```
* Since it does not output any error log information, I cannot troubleshoot the problem of determine its source. 
* Could you provide some examples of how one can run the pipeline partially. i.e command lines for different parts and list of the mandatory options for each? Or the any tips on configuring the test run that one could make? 
* The call of _RNAnue subcall --config_ on github page is the only example of usage so far. I believe some docu on running the separate parts of RNAnue pipeline might be generally usefull for people. 

* I also had problem with unrecognized parameters in the original config template file.
Unless corresponding lines are not removed/commented from the config file, running  
 _/RNAnue/build/RNAnue subcall -c /data/meyer/egor/RNAnue_pipeline/params.cfg_
produces the errors like: 

  ```
  after parameters
  unrecognised option 'mapquality'
  unrecognised option 'wsize'
  unrecognised option 'exclclipping'
  ```

Here is some details on my configuration: 
* The HPC evrironment that I am using has the Sigularity container toolset. It should be comptible with the docker. Invoking the RNAnue from container seems to be responding, i.e  I can read the help messages and recieve errors when the options lines are purposly made incorrect. 

* The gff and fna files that I use are downloaded from ncbi database and not changed ecxept  '3' to '.gff'  has been added to make fileformat  '.gff3'

* The structure of paired-end reads (one PE sample, no controls) is following
```
	/data/egor/RNAnue_pipeline/paired/trtms/R1.fastq
	/data/egor/RNAnue_pipeline/paired/trtms/R1.fastq

In the config file:
 _trtms = /data/egor/RNAnue_pipeline/paired/trtms_ 
```
I would greately appreciate any help

[params.cfg.txt](https://github.com/Ibvt/RNAnue/files/6892403/params.cfg.txt)

**Comment by riasc** [comment]
Hi @Egors01,
thanks again for the issue. The problem seems to be occurring on a specific set of identifiers in the .fastq files. I pushed a new image that should resolve that. Also the ending of the files is .fastq? (not .fq). Haven't captured this before. 

I'm currently testing this on a singularity instance. Other than that your setup seems fine. Also, it seems the container was behind a few commits such that the parameters files couldn't be specified correctly. Sorry about that. Could you please try that with the recent image? I tried to make the description a bit more detailed and will try to describe the individual steps in more detail these days.. In principle, each subcall can be executed separately... preproc, align, detect, analysis..

You did execute it with the "complete" subcall (<subcall> as "complete") right? I think I haven't captured a non-specified subcall. Which I maybe should do. 

Rich

[params.cfg-2.txt](https://github.com/Ibvt/RNAnue/files/7031511/params.cfg-2.txt)

**Comment by Egors01** [comment]
Hi, Rich 

Thanks a lot. 
I am going to try with the new container build soon. 

The reads are with the .fastq extension. I will try with .fq as well. 
I am not sure I understand the "complete" definition. From container I was running  /RNAnue/build/RNAnue subcall -c <path_to_configuration_file>  which I wanted to make the run of all steps. 

Best 
Egor

**Comment by riasc** [comment]
Hi Egor,
ah yes I think I didn't put the subcall in "<>", thats why I guess it was a bit confusing. You would have to execute /RNAnue/build/RNAnue complete -c <path_to_configuration_file> or just replace subcall with the individual steps.. preproc, align etc.. Haven't put that in the README.. Thanks.

**Comment by Egors01** [comment]
Hi, Rich

I have tried to run the container build again, and it looks unusable in its current state.
Below I provide the list of the problems that I have encountered. 

* I use the same config file for all RNanue calls. 
* Compared to the config file in the beginning of this thread, the paths in config files were modified to match the mounting point in the container "--bind /data/egor:/mnt " flag 
The list of the problems for container build is following. 

1. RNAnue complete execution fails with an error. 
 Call:

> singularity exec --bind /data/egor:/mnt ./rnanue_latest.sif /RNAnue/build/RNAnue complete -c /mnt/influenza_splash/2cimpl/RNAnue_pipeline/params_clean_container

Output: 
>   RNAnue v0.1.0 - Detect RNA-RNA interactions from Direct-Duplex-Detection (DDD) data.
>   complete analysis
>   created instance of sequence RickShaw
>   create lookup table using /mnt/influenza_splash/2cimpl/paired/r1r2-adapters.fa
>   AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
>   AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
> 	  "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output" already exists.
> 	   created "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/complete"
>   terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::ptree_bad_path>'
>     what():  No such node (complete)
>   Aborted
> 

2. 
Container apparently does not contain/cannot find segemehl, so it is impossible to run any step other than "preproc". 
Error logs on RANue align:

> $ singularity exec --bind /data/egor:/mnt ./rnanue_latest.sif /RNAnue/build/RNAnue align -c /mnt/influenza_splash/2cimpl/RNAnue_pipeline/params_clean_container
> RNAnue v0.1.0 - Detect RNA-RNA interactions from Direct-Duplex-Detection (DDD) data.
> reads the data to align
> *** collect the data
> 	ctrls:	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/preproc/ctrls"
> 		...has been found in the filesystem!
> 	trtms:	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/preproc/trtms"
> 		...has been found in the filesystem!
> 		wsn1_a
> retrieve output 
> align called within Base
> create align object
> segemehl index found on filesystem
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output" already exists.
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align" already exists.
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align/ctrls" already exists.
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align/trtms" already exists.
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align/trtms/wsn1_a" already exists.
> start align
> sh: 1: segemehl.x: not found
> segemehl.x -S  -A 90 -U 15 -W 80 -Z 15 -t 4 -m 20 -i /mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/GCA_000001405.15_GRCh38_no_alt_analysis_set.idx -d /mnt/influenza_splash/genome/hg38_chr/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -q /mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/preproc/trtms/wsn1_a/wsn1_a_preproc.fastq -o /mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align/trtms/wsn1_a/wsn1_a_preproc_matched.sam
> "Neeeeinnnnnn" - Biggi

3. The similar error on RANnue detect. The container cannot find ViennaRNA.   
I have bypassed the upstream RANue align error with the manually compiled RNAnue build, so the following call takes the output of RNAnue aligns. 

> $ singularity exec --bind /data/egor:/mnt ./rnanue_latest.sif /RNAnue/build/RNAnue clustering -c /mnt/influenza_splash/2cimpl/RNAnue_pipeline/params_clean_container
Output:
> RNAnue v0.1.0 - Detect RNA-RNA interactions from Direct-Duplex-Detection (DDD) data.
> *** collect the data
> \### WARNING - this call runs RNAnue without control data
> \### WARNING - "--ctrls" has not been set
> 	trtms:	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/align/trtms"
> 		...has been found in the filesystem!
> 		wsn1_a
> 	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output" already exists.
> 	 created "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/detect"
> 	 created "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/detect/trtms"
> 	 created "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/detect/trtms/wsn1_a"
> sh: 1: RNAcofold: not found
> Segmentation fault

3. When there is no control data, RNAnue align and detect steps also crash with the error if the folder "<outdir>/<subprogram_name>/ctrls" is not created manually. 
<outdir> is the output folder that is specifid in the config file. <subprogram_name> is align, preproc etc.
Call 
> $ singularity exec --bind /data/egor:/mnt ./rnanue_latest.sif /RNAnue/build/RNAnue align -c /mnt/influenza_splash/2cimpl/RNAnue_pipeline/params_clean_container
Output
> RNAnue v0.1.0 - Detect RNA-RNA interactions from Direct-Duplex-Detection (DDD) data.
> reads the data to align
> *** collect the data
> 	ctrls:	"/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/preproc/ctrls"
> \### ERROR - "/mnt/influenza_splash/2cimpl/RNAnue_pipeline/rnanue-output/preproc/ctrls"could not be found in the filesystem!

The config file that I use is attached 
[params_clean_container.txt](https://github.com/Ibvt/RNAnue/files/7209718/params_clean_container.txt)
